spring:
  profiles:
    active:
      - dev
---
server:
  port: 8201
server:
  port: 8202
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eurek-dev.com:7001/eureka/
---
spring:
  profiles: test #测试环境
  application:
    name: microservicecloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
